[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
bevy = { workspace = true }
bevy_remote_inspector = { workspace = true }
bevy_renet = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
